00 01 dev and cf
NerdPractitioner/stelligent-university pull request #5
Opened 2021-06-28 18:10 UTC by NerdPractitioner

# Requirements for Contributing a Bug Fix

- Fill out the template below. Any pull request that does not include enough
  information to be reviewed in a timely manner may be closed at the maintainers'
  discretion.

## Identify the Bug

## Description of the Change

## Alternate Designs

## Possible Drawbacks

## Verification Process

## Release Notes

2021-06-29 04:54 UTC, NerdPractitioner commented
Reopening pull request for first two branches that now pass markdown linting

2021-07-06 16:18 UTC, thegonch commented on 00-dev-environment/worksheet.md
> +
So while aws-vault is great for our usage internally at Stelligent, it may not always be an option on a client.  So other options include:  update the ~/.aws/credentials file, set the various AWS Environment variables, possibly source the script and create alias commands so that it pulls the mfa script as needed.

2021-07-06 16:18 UTC, thegonch commented on 00-dev-environment/worksheet.md
> +
The AWS Environment variable referred to here is `AWS_PROFILE`. This env var can't be set to anything but `default` or the `aws sts get-session-token` command fails. It's best to keep it unset for the command to always succeed.

2021-07-06 16:18 UTC, thegonch commented on 00-dev-environment/worksheet.md
> +
The other methods to gain access without using keys include IAM users, roles, and policies.

2021-07-06 16:18 UTC, thegonch commented on 01-cloudformation/worksheet.md
> +
Another feature is that naturally YAML allows for comments where JSON does not (unless you use a package/extension like https://pypi.org/project/json-cfg/).

2021-07-06 16:19 UTC, thegonch requested changes

2021-07-06 16:19 UTC, thegonch commented on 01-cloudformation/worksheet.md
> +
This answer appears to be missing.

2022-03-30 16:44 UTC, merged